#!/usr/bin/env bash
# Interactive AVFoundation capture device index for make preview (macOS).
# Writes repo-root local.mk (gitignored), preserving ARDUINO_PORT if set.
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "set-video targets macOS ffmpeg + AVFoundation (make preview)." >&2
  echo "On other systems, put VIDEO_DEVICE := <index> in local.mk or pass VIDEO_DEVICE to make." >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
LOCAL_MK="local.mk"

read_port_from_local_mk() {
  if [[ ! -f "$LOCAL_MK" ]]; then
    echo ""
    return 0
  fi
  grep -E '^ARDUINO_PORT[[:space:]]*(\?|:)=' "$LOCAL_MK" 2>/dev/null | head -1 | \
    sed -E 's/^ARDUINO_PORT[[:space:]]*[^:]*:[[:space:]]*//' | tr -d '"' || true
}

write_local_mk() {
  local port="$1"
  local video="$2"
  {
    echo "# Local device targets — generated by scripts/set-board.sh / set-video.sh (gitignored)"
    if [[ -n "$port" ]]; then
      echo "ARDUINO_PORT := $port"
    fi
    echo "VIDEO_DEVICE := $video"
  } > "$LOCAL_MK"
}

ARDU_PREV="$(read_port_from_local_mk)"

echo "=== Video capture devices (ffmpeg -f avfoundation -list_devices) ==="
echo "ffmpeg is run with no capture file so it can only enumerate devices; it then"
echo "tries to open an empty path and prints Error opening input — that is normal."
echo
OUT="$(mktemp)"
if ! ffmpeg -hide_banner -f avfoundation -list_devices true -i "" 2>"$OUT"; then
  : # ffmpeg exits non-zero; device list is on stderr
fi
# Show only the video-device block (drop audio + trailing open errors)
awk '
  /AVFoundation video devices:/ { v = 1; print; next }
  /AVFoundation audio devices:/ { v = 0; next }
  v { print }
' "$OUT"
echo

# Parse [N] Name lines from ffmpeg AVFoundation listing (video devices only)
entries=()
while IFS= read -r line; do
  [[ -n "$line" ]] && entries+=("$line")
done < <(python3 - "$OUT" <<'PY'
import re, sys
path = sys.argv[1]
text = open(path, "r", errors="replace").read()
in_video = False
for line in text.splitlines():
    low = line.lower()
    if "avfoundation video devices" in low or (
        "video devices" in low and "avfoundation" in low
    ):
        in_video = True
        continue
    if "audio devices" in low and "avfoundation" in low:
        in_video = False
        continue
    if not in_video:
        continue
    m = re.search(r"\[(\d+)\]\s+(.+)$", line)
    if m:
        print(m.group(1) + "\t" + m.group(2).strip())
PY
)

rm -f "$OUT"

if ((${#entries[@]} == 0)); then
  echo "Could not parse device list. Enter ffmpeg device index manually (often 0 or 1)."
  read -r -p "VIDEO_DEVICE [0]: " reply || true
  vid="${reply:-0}"
  write_local_mk "$ARDU_PREV" "$vid"
  echo "Wrote $ROOT/$LOCAL_MK — VIDEO_DEVICE := $vid"
  exit 0
fi

echo "Capture devices:"
i=1
declare -a idxs
for e in "${entries[@]}"; do
  idx="${e%%	*}"
  name="${e#*	}"
  idxs+=("$idx")
  echo "  [$i] [$idx] $name"
  ((i++)) || true
done
echo

default_idx="${idxs[0]}"
# Prefer a name containing usb / video / capture (case-insensitive; bash 3–safe)
for e in "${entries[@]}"; do
  idx="${e%%	*}"
  name="${e#*	}"
  nl=$(echo "$name" | tr '[:upper:]' '[:lower:]')
  if [[ "$nl" == *usb* ]] || [[ "$nl" == *video* ]] || [[ "$nl" == *capture* ]]; then
    default_idx="$idx"
    break
  fi
done

read -r -p "Enter menu number 1-${#entries[@]}, or ffmpeg index [${default_idx}]: " reply || true
reply="${reply:-}"
chosen="$default_idx"
if [[ -z "$reply" ]]; then
  chosen="$default_idx"
elif [[ "$reply" =~ ^[0-9]+$ ]] && (( reply >= 1 && reply <= ${#entries[@]} )); then
  ent="${entries[$((reply - 1))]}"
  chosen="${ent%%	*}"
else
  chosen="$reply"
fi

write_local_mk "$ARDU_PREV" "$chosen"

echo
echo "Wrote $ROOT/$LOCAL_MK"
echo "  VIDEO_DEVICE := $chosen"
[[ -n "$ARDU_PREV" ]] && echo "  (left ARDUINO_PORT unchanged)"
echo "Run: make preview"
