#!/usr/bin/env bash
# Interactive serial port selection for Arduino upload/monitor.
# Writes repo-root local.mk (gitignored), preserving VIDEO_DEVICE if set.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
LOCAL_MK="local.mk"
# Typical default when the board is not in the detected list (macOS vs Linux)
if [[ "$(uname -s)" == "Darwin" ]]; then
  DEFAULT_PORT="/dev/cu.usbmodem101"
else
  DEFAULT_PORT="/dev/ttyACM0"
fi

read_video_from_local_mk() {
  if [[ ! -f "$LOCAL_MK" ]]; then
    echo ""
    return 0
  fi
  # Match "VIDEO_DEVICE := value" or ?= (strip quotes)
  grep -E '^VIDEO_DEVICE[[:space:]]*(\?|:)=' "$LOCAL_MK" 2>/dev/null | head -1 | \
    sed -E 's/^VIDEO_DEVICE[[:space:]]*[^:]*:[[:space:]]*//' | tr -d '"' || true
}

write_local_mk() {
  local port="$1"
  local video="$2"
  {
    echo "# Local device targets — generated by scripts/set-board.sh / set-video.sh (gitignored)"
    echo "ARDUINO_PORT := $port"
    if [[ -n "$video" ]]; then
      echo "VIDEO_DEVICE := $video"
    fi
  } > "$LOCAL_MK"
}

VIDEO_PREV="$(read_video_from_local_mk)"

echo "=== Connected boards (arduino-cli board list) ==="
arduino-cli board list 2>/dev/null || true
echo

# macOS cu.* and common Linux serial paths (bash 3.2–compatible; no mapfile)
ports=()
while IFS= read -r line; do
  [[ -n "$line" ]] && ports+=("$line")
done < <(arduino-cli board list 2>/dev/null | \
  grep -oE '/dev/(cu\.[^[:space:]]+|ttyACM[0-9]+|ttyUSB[0-9]+)' | sort -u)

chosen=""
if ((${#ports[@]} > 0)); then
  echo "Serial ports detected:"
  i=1
  for p in "${ports[@]}"; do
    mark=""
    [[ "$p" == "$DEFAULT_PORT" ]] && mark=" (default)"
    echo "  [$i] $p$mark"
    ((i++)) || true
  done
  echo
  # Prefer the usual Feather path, then any usbmodem*, else stay optimistic (not e.g. Bluetooth)
  chosen="$DEFAULT_PORT"
  if printf '%s\n' "${ports[@]}" | grep -qxF "$DEFAULT_PORT"; then
    chosen="$DEFAULT_PORT"
  else
    for p in "${ports[@]}"; do
      [[ "$p" == *usbmodem* ]] && { chosen="$p"; break; }
    done
  fi
  read -r -p "Enter number 1-${#ports[@]}, or a full /dev path [${chosen}]: " reply || true
  reply="${reply:-}"
  if [[ -z "$reply" ]]; then
    :
  elif [[ "$reply" =~ ^[0-9]+$ ]] && (( reply >= 1 && reply <= ${#ports[@]} )); then
    chosen="${ports[$((reply - 1))]}"
  elif [[ "$reply" == /dev/* ]]; then
    chosen="$reply"
  else
    echo "Unrecognized input; keeping suggested port: $chosen" >&2
  fi
else
  echo "No /dev/cu.* ports found in board list."
  echo "Using optimistic default: $DEFAULT_PORT"
  read -r -p "Enter /dev path, or Enter to accept [${DEFAULT_PORT}]: " reply || true
  chosen="${reply:-$DEFAULT_PORT}"
fi

write_local_mk "$chosen" "$VIDEO_PREV"

echo
echo "Wrote $ROOT/$LOCAL_MK"
echo "  ARDUINO_PORT := $chosen"
[[ -n "$VIDEO_PREV" ]] && echo "  (left VIDEO_DEVICE unchanged)"
echo "Run: make upload   make monitor"
